---
- name: Install sdkman
  shell: |
    export SDKMAN_DIR="{{ user_home }}/.sdkman"
    curl -s "https://get.sdkman.io?rcupdate=false" | bash
  args:
    creates: "{{ user_home }}/.sdkman/bin/sdkman-init.sh"
  changed_when: false
