---
- name: Install sdkman
  shell: |
    export SDKMAN_DIR="{{ ansible_env.HOME }}/.sdkman"
    curl -s "https://get.sdkman.io?rcupdate=false" | bash
  args:
    creates: "{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh"
  changed_when: false
