---
- name: Install nvm
  shell: |
    export HOME=/home/faraz
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    creates: "/home/faraz/.config/nvm/nvm.sh"
