---
- name: Install rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
  args:
    creates: "{{ user_home }}/.cargo/bin/rustup"
  changed_when: false
