---
- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
    version: master
  register: pyenv_install

- name: Install pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"
    version: master
